package com.example.tickets_api.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * An application user stored in MongoDB, used for authentication and
 * authorization. The {@code password} is always persisted hashed (BCrypt),
 * never in plain text.
 */
@Document
public class AppUser {

    /** Unique identifier generated by MongoDB. */
    @Id
    private String id;

    /**
     * Login name. Marked unique so two accounts cannot share a username; the
     * unique index is created at startup because {@code auto-index-creation} is
     * enabled in application.yml.
     */
    @Indexed(unique = true)
    private String username;

    /** BCrypt-hashed password. */
    private String password;

    /** Authorization role (e.g. {@code ADMIN}), mapped to a Spring Security authority. */
    private String role;

    /** No-args constructor required by Spring Data to instantiate the document. */
    public AppUser() {}

    /**
     * Creates a user.
     *
     * @param username the unique login name
     * @param password the already-hashed password
     * @param role     the authorization role
     */
    public AppUser(String username, String password, String role){
        this.username = username;
        this.password = password;
        this.role = role;
    }

    public String getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }

    /**
     * Diagnostic representation. Deliberately omits {@code password} so the
     * credential never leaks into logs or error messages.
     */
    @Override
    public String toString() {
        return "AppUser{" +
                "username='" + username + '\'' +
                ", id=" + id +
                ", role='" + role + '\'' +
                '}';
    }
}
