package com.example.tickets_api.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * A support ticket stored in the "tickets" MongoDB collection.
 * <p>
 * Each ticket has a title and description provided by the user,
 * plus a {@link Status} and {@link Priority} that track its lifecycle.
 */

@Document(collection = "tickets")
public class Ticket {

    /** Unique identifier generated by MongoDB. */
    @Id
    private String id;

    /** Short summary of the issue. */

    private String title;

    /** Detailed explanation of the issue. */
    
    private String description;

    /** Current lifecycle state of the ticket. */
    private Status status;

    /** Urgency level of the ticket. */
    private Priority priority;

    public Ticket() {}

    /**
     * Creates a new ticket. The id is left null and assigned by MongoDB on save.
     */
    public Ticket(String title, String description, Status status, Priority priority) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.priority = priority;
    }

    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public Status getStatus() {
        return status;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    @Override
    public String toString() {
        return "Ticket{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                ", priority=" + priority +
                '}';
    }
}
